### PR TITLE
Support Qovery as a deployment option

### PR DESCRIPTION
**Pull request by arnaudjnn**
## Description of the change

We want to offer a quick and free way to deploy Rudderstack in production.

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Docs

### Development

- [x] Lint rules pass locally
- [x] The code changed/added as part of this pull request has been covered with tests
- [x] All tests related to the changed code pass in development

### Code review 

- [x]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [x] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [x] Changes have been reviewed by at least one other engineer
- [x] Issue from task tracker has a link to this pull request

### CODE REVIEW

**Review by ameypv-rudder — COMMENTED** [review]
Hi @arnaudjnn, thanks for the PR.

I have a request - could you please add step-by-step screenshots for the steps, so that the users can easily verify them?

**Comment by arnaudjnn** [comment]
Hi @ameypv-rudder,

I just added the images to help with the Deploy with Qovery tutorial.

Let me know,

**Comment by arnaudjnn** [comment]
@ameypv-rudder Did you have the time to have a look at the updates?

Let me know

**Comment by ameypv-rudder** [comment]
Hi @arnaudjnn, apologies for the delayed response. 

I've been in consultation with the team regarding this, and I have some thoughts I'd like to discuss with you - over email, if that's okay? 

Let me know.

**Comment by arnaudjnn** [comment]
Hi @ameypv-rudder,

Of course! I think we could chat or have a call here: http://discord.qovery.com/

Qovery's CEO @evoxmusic can join us if you want to.

Let me know,

**Pull request closed without merging**
