### PR TITLE
Contextual fields section update

### PR DESCRIPTION
**Pull request by ameypv-rudder**
## What do these changes do?

> Updated contextual fields section to clarify the automatically collected fields vs. the ones that are not automatically collected.

## Type of documentation

- [ ] New documentation
- [ ] Documentation update
- [x] Hotfix

### CODE REVIEW

**Review by ishachopra0401 — APPROVED** [review]

**Comment by esadek** [comment]
The first table states that `app.name`, `app.version`, and `app.build` are automatically collected by the Android and iOS SDKs, however, the second table states that these are not automatically collected?

**Comment by esadek** [comment]
The JavaScript SDK automatically collects `app.build`, `app.name`, `app.namespace` and `app.version`, but the first table states that these are not automatically collected.

**Comment by ameypv-rudder** [comment]
@esadek I had a chat with @saikumarrs re: the JS SDK and shared your feedback with him. He mentioned that `context.app` is not applicable for the JS SDK. 

re: the other feedback, I've restructured the doc a bit to clarify a few things - the first table defines **all** the supported contextual fields. I've added a subsection that explicitly lists the fields that are automatically collected by each SDK.

LMK if this approach makes more sense.

**Comment by esadek** [comment]
@ameypv-rudder I am seeing that the JS SDK automatically collects `context.app` data.

SCR-20221112-jjl

**Comment by ameypv-rudder** [comment]
> @ameypv-rudder I am seeing that the JS SDK automatically collects `context.app` data.
> 
> SCR-20221112-jjl

@esadek that's right - however, as per my discussion with Sai, the plan is to stop automatically collecting these fields.

@saikumarrs please correct me if I'm wrong here

**Comment by esadek** [comment]
@ameypv-rudder Okay that makes sense.

**Pull request merged**
