### PR TITLE
Fix Mailchimp example casing

### PR DESCRIPTION
**Pull request by keithbrink**
## Description of the change

Mailchimp casing is wrong in the examples

## Type of documentation

- [ ] New documentation
- [X] Documentation update
- [ ] Bug fix

### CODE REVIEW

**Review by ameypv-rudder — APPROVED** [review]

**Comment by ameypv-rudder** [comment]
Thank you @keithbrink for highlighting and pushing this fix!

**Comment by akashrpo** [comment]
@keithbrink Thanks for highlighting. Unfortunately, we cannot accommodate this change in our docs currently as this will be a breaking change for existing customers where the existing key `MailChimp` plays an important role in our transformation. Ref - [Mailchimp](https://github.com/rudderlabs/rudder-transformer/blob/master/v0/destinations/mailchimp/transform.js#L129). Since this is not a burning requirement as of now we can sure take it up later.

**Comment by utsabc** [comment]
@keithbrink To highlight more this change will be affecting the existing pipelines we have for all our users, we are planning to incorporate such changes with backward compatibility. Once this framework is in place we will take it up.
again thanks a lot for raising this PR

**Comment by keithbrink** [comment]
@akashrpo @utsabc I'm confused - this change is to align with the rest of the docs: https://www.rudderstack.com/docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/#common-destination-names

**Comment by ameypv-rudder** [comment]
> @akashrpo @utsabc I'm confused - this change is to align with the rest of the docs: https://www.rudderstack.com/docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/#common-destination-names

@keithbrink You're right - this is a discrepancy. We've pushed a fix for this doc: https://www.rudderstack.com/docs/stream-sources/rudderstack-sdk-integration-guides/rudderstack-javascript-sdk/#common-destination-names for consistency. Tracking the change in this [PR](https://github.com/rudderlabs/rudderstack-docs/pull/497).

**Comment by keithbrink** [comment]
Got it, I changed the wrong one. My apologies, I'll close this one, thanks for the fix.

**Pull request closed without merging**
