### PR TITLE
Update VDM doc to specify Customer.io support

### PR DESCRIPTION
**Pull request by ameypv-rudder**
## Description of the change

> Updated the VDM doc to include support for Customer.io as a destination
> Updated the doc to remove any formatting inconsistencies
> Replaced screenshots with the same screenshots with doc-specific names

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

### CODE REVIEW

**Comment by ashishRudder** [comment]
Please add the description and mark checklist. I am not sure about the procedure in rudderstack-docs repo but we have started following compliance instructions throughout all the repos.

**Comment by ashishRudder** [comment]
Question: why are we adding new images? Is there any difference?

**Comment by ameypv-rudder** [comment]
> Please add the description and mark checklist. I am not sure about the procedure in rudderstack-docs repo but we have started following compliance instructions throughout all the repos. For ref: https://www.notion.so/rudderstacks/Engineering-Compliance-Process-3bbafb7a913749bcadd5f2958b8469b7

sounds good. I've updated the PR description. We don't follow this for the docs repo as the PR names are usually self-explanatory, but it's a good practice to do this going forward. Will encourage everyone to do the same.

**Comment by ameypv-rudder** [comment]
> Question: why are we adding new images? Is there any difference?

There is no difference. Just that the previous images were named randomly e.g. 1(25).png, etc. Replaced those with doc-specific image names.

**Comment by ashishRudder** [comment]
LGTM

**Review by ashishRudder — APPROVED** [review]

**Pull request merged**
