### PR TITLE
Gh badges

### PR DESCRIPTION
**Pull request by avinder-red-crackle**
## Props

**`label`** => Required (Optional if repo is provided)

**`message`** => Required (Optional if repo is provided)

**`color`** => Required (Optional if repo is provided)

**`style`** => Optional

**`logo`** => Optional

**`url`** => Optional

**`repo`** => Optional

## Usage

```jsx
<GhBadge
  label={'Stability'}
  message={'Beta'}
  color={'blueviolet'}
  style={'for-the-badge'}
  logo={'github'}
  url={'https://rudderstack.com/enterprise-quote'}
/>
```

```jsx
<GhBadge
  url={'https://www.npmjs.com/package/rudder-sdk-cordova/'}
  repo={'npm/v/rudder-sdk-cordova'}
  style={'flat'}
/>
```

## Examples

label={'Stability'} message={'Beta'} color={'blueviolet'} style={'for-the-badge'} logo={'github'}

label={'Stability'} message={'Beta'} color={'blueviolet'} style={'for-the-badge'} logo={'github'} style={'for-the-badge'}

label={'Stability'} message={'Beta'} color={'blueviolet'} style={'for-the-badge'} logo={'github'} style={'for-the-badge'} logo={'github'}

repo={'npm/v/rudder-sdk-cordova'}

label={'Github'} repo={'github/v/release/rudderlabs/analytics-go'}

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1202402542887674

### CODE REVIEW

**Review by pfd — CHANGES_REQUESTED** [review]
This looks great @avinder-red-crackle — and thank you for adding the additional props for style and logo. I was going through and updating the docs with the component and I noticed we also have some that are not static, like 
https://img.shields.io/github/v/release/rudderlabs/analytics-go.svg?label=Github, which render the version number in the badge.

We would just want that to show the latest version in the case of a RudderStack SDK, so maybe a prop called `repo` or something where the value replaces the static badge URL? what do you think?

**Comment by avinder-red-crackle** [comment]
@pfd `repo` prop has been added to the GhBadge component. Some examples are included in the PR.

**Review by pfd — APPROVED** [review]
Thanks @avinder-red-crackle ! Looks great. I am going to merge and we'll update the rest of the links later

**Comment by avinder-red-crackle** [comment]
Thanks @pfd

**Pull request merged**
