### PR TITLE
Update .net.md

### PR DESCRIPTION
**Pull request by esadek**
## Description of the change

> Description here

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

### CODE REVIEW

**Review by arnab-p — APPROVED** [review]
LGTM, Please update the code snippets with 2-space indentation and are good to merge.

**Comment by esadek** [comment]
Changed code block indentation to 2 spaces.

**Comment by ameypv-rudder** [comment]
Since this PR contains the older markdown format and all the changes have been ported here: https://github.com/rudderlabs/rudderstack-docs/pull/271, let me know if I can close this PR.

**Comment by esadek** [comment]
> Since this PR contains the older markdown format and all the changes have been ported here: #271, let me know if I can close this PR. @esadek

Sounds good. Thanks Amey

**Pull request closed without merging**
