### PR TITLE
Docs 404

### PR DESCRIPTION
**Pull request by kilajyot**
Adding a 404 Page

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1202378674553427
  - https://app.asana.com/0/0/1202378674553421

### CODE REVIEW

**Review by gpxl — CHANGES_REQUESTED** [review]
The preview deploy is not rendering 404s correctly. https://deploy-preview-639--rudderstack-docs-staging.netlify.app/foobar

**Review by pfd — COMMENTED** [review]
- Please make the page title "Page not found"
- Can you add the following text to the page: "Sorry, but that page has set sail. Let's get you back on course."
- Make the button smaller- it takes up the whole width of the page
- Position the button below the paragraph text
- Button text: Return to docs home

**Review by pfd — CHANGES_REQUESTED** [review]
Looks nice- we just need the page `title` to be "Page not found"

**Review by pfd — APPROVED** [review]
👍🏻

**Pull request merged**
