### PR TITLE
FTR update for warehouse destinations

### PR DESCRIPTION
**Pull request by ameypv-rudder**
## What do these changes do?

> Added role based auth support in the supported WH destination docs
> Cleaned up the doc metas and some introductory content.
> Updated the supported destination list [here](https://www.rudderstack.com/docs/destinations/aws-iam-role-for-rudderstack/).

Preview: [Here](https://rudderstack-docs-cznh9kyaa-rudder-stack.vercel.app/destinations/aws-iam-role-for-rudderstack/)

## Type of documentation

- [ ] New documentation
- [x] Documentation update
- [ ] Hotfix

### CODE REVIEW

**Comment by achettyiitr** [comment]
@ameypv-rudder 
Should we also mention `Role-based Authentication` in the Connection settings as well for the supported destinations?

**Comment by ameypv-rudder** [comment]
> @ameypv-rudder Should we also mention `Role-based Authentication` in the Connection settings as well for the supported destinations?

we do in some cases where we explain each setting in the doc, e.g. S3 data lake, Redshift. 

For some destinations, we simply redirect to the S3 doc for the object storage settings, where the Role based auth is explained in detail. Adding a mention of just the Role based Auth setting in such cases will only lead to some confusion.

**Comment by ameypv-rudder** [comment]
@achettyiitr happy to jump on a call to clarify more, if needed.

**Comment by ameypv-rudder** [comment]
@achettyiitr @koladilip are we good to proceed here?

**Comment by achettyiitr** [comment]
> @achettyiitr @koladilip are we good to proceed here?

Control plane release is postponed to tomorrow.

**Pull request merged**
