### PR TITLE
Add Vitally destination

### PR DESCRIPTION
**Pull request by jason-vitally**
## What do these changes do?

Adds documentation for new Vitally destination

## Related issues

[config-generator](https://github.com/rudderlabs/config-generator/pull/47)
[transformer](https://github.com/rudderlabs/rudder-transformer/pull/1795)
[rudderstack-docs](https://github.com/rudderlabs/rudderstack-docs/pull/1113)

## Type of documentation

- [x] New documentation
- [ ] Documentation update
- [ ] Hotfix

### CODE REVIEW

**Comment by aashishmalik** [comment]
@jason-vitally we will release this as cloud mode, can you remove supported from device mode.

**Comment by jason-vitally** [comment]
@aashishmalik Done!

**Comment by ameypv-rudder** [comment]
@aashishmalik @ItsSudip could you please approve this PR so we can proceed?

**Review by ItsSudip — APPROVED** [review]

**Comment by ameypv-rudder** [comment]
@jason-vitally The doc is now live :) Hence, closing this PR.

**Pull request closed without merging**
